export type ContentType = "text" | "drawing";

export interface GameContent {
  id: number;
  type: ContentType;
  content: string; // Text content or SVG component name
  prompt?: string; // The question or prompt that was asked
  source: "ai" | "child";
  context: string; // "Generated by GPT-4" or "By Emma, age 5"
  funFact?: string;
}

export const gameContent: GameContent[] = [
  // TEXT CONTENT - Questions & Answers
  {
    id: 1,
    type: "text",
    prompt: "Why is the sky blue?",
    content: "Because God painted it blue with a really big brush and he picked blue because it's his favorite color. And the clouds are white because he ran out of blue paint sometimes.",
    source: "child",
    context: "By Mia, age 5",
    funFact: "Mia also believes God has a pet dinosaur"
  },
  {
    id: 2,
    type: "text",
    prompt: "Why is the sky blue?",
    content: "The sky is blue because the sun's light bounces around in the air and the blue parts bounce the most so that's what we see! It's like when you throw a bouncy ball and it goes everywhere.",
    source: "ai",
    context: "Generated by GPT-4 (prompted to sound like a child)",
    funFact: "AI was given the instruction: 'Explain like you're 5 years old'"
  },
  {
    id: 3,
    type: "text",
    prompt: "What happens when you die?",
    content: "You turn into a ghost and fly around and you can go through walls which is really cool. My grandma is a ghost now and she lives in the clouds and eats cloud candy.",
    source: "child",
    context: "By Jayden, age 6",
    funFact: "Jayden drew a picture of 'cloud candy' - it looks like cotton candy"
  },
  {
    id: 4,
    type: "text",
    prompt: "What happens when you die?",
    content: "When you die you go to sleep forever and your body goes back into the ground to help flowers grow. It's like recycling but for people. Then your spirit goes to a happy place.",
    source: "ai",
    context: "Generated by Claude (prompted to explain like a child)",
    funFact: "The AI avoided mentioning anything too dark"
  },
  {
    id: 5,
    type: "text",
    prompt: "Why do people get married?",
    content: "Because they love each other SO much that they want to have a big party with cake. And then they live together forever and the lady gets to wear a princess dress for ONE DAY.",
    source: "child",
    context: "By Sophie, age 5",
    funFact: "Sophie's parents got married in Vegas with no cake - she was very disappointed when she learned this"
  },
  {
    id: 6,
    type: "text",
    prompt: "Why do people get married?",
    content: "People get married because when you really really like someone, you want to be their best friend forever and share your toys and your house. It's like a super pinky promise!",
    source: "ai",
    context: "Generated by GPT-4 (child mode)",
    funFact: "The AI struggled not to mention taxes"
  },
  {
    id: 7,
    type: "text",
    prompt: "Explain how a car works",
    content: "You put juice in it and turn the key and it goes VROOM. The wheels spin because of the engine which is like the car's tummy. When you push the pedal it tells the tummy to go faster.",
    source: "child",
    context: "By Lucas, age 6",
    funFact: "Lucas calls gasoline 'car juice'"
  },
  {
    id: 8,
    type: "text",
    prompt: "Explain how a car works",
    content: "A car drinks special gas that makes fire inside it (but safe fire). The fire pushes things that spin the wheels super fast. The steering wheel tells the wheels where to go!",
    source: "ai",
    context: "Generated by Claude (child explanation)",
    funFact: "Three different humans couldn't tell this was AI"
  },
  {
    id: 9,
    type: "text",
    prompt: "What is money?",
    content: "It's paper that grown-ups trade for stuff. You can't just make your own though because that's cheating. My dad goes to work to get more money and he's always tired after.",
    source: "child",
    context: "By Emma, age 7",
    funFact: "Emma once tried to pay for ice cream with a drawing of money"
  },
  {
    id: 10,
    type: "text",
    prompt: "What is money?",
    content: "Money is special paper that lets you buy things you want. You have to do work or jobs to earn it. It's like trading but easier because everyone agrees the paper is worth stuff.",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "This explanation is arguably better than many economics textbooks"
  },
  {
    id: 11,
    type: "text",
    prompt: "What is love?",
    content: "Love is when you give someone the last chicken nugget even though you really wanted it. And when mommy looks at daddy like he's a donut.",
    source: "child",
    context: "By Aiden, age 5",
    funFact: "Aiden's mom really loves donuts"
  },
  {
    id: 12,
    type: "text",
    prompt: "What is love?",
    content: "Love is a warm fuzzy feeling in your heart when you care about someone lots and lots. It makes you want to hug them and be nice to them and share your snacks.",
    source: "ai",
    context: "Generated by Claude",
    funFact: "The 'share your snacks' line was added to sound more authentic"
  },
  {
    id: 13,
    type: "text",
    prompt: "How does the internet work?",
    content: "It's invisible strings that go everywhere and carry pictures and videos super fast. Like magic but with computers. My iPad finds the strings and shows me YouTube.",
    source: "child",
    context: "By Oliver, age 6",
    funFact: "Oliver thinks WiFi is literally invisible spaghetti"
  },
  {
    id: 14,
    type: "text",
    prompt: "How does the internet work?",
    content: "The internet is like a giant spider web that connects all the computers in the world. When you click something, little messages zoom through wires super fast to get what you want!",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "The spider web analogy is commonly used by AI when simplifying"
  },
  {
    id: 15,
    type: "text",
    prompt: "What are dreams?",
    content: "When you sleep your brain makes movies in your head. Sometimes they're scary but they're not real. I had a dream I was a pizza once.",
    source: "child",
    context: "By Chloe, age 5",
    funFact: "Chloe was very upset when she woke up and wasn't a pizza anymore"
  },
  {
    id: 16,
    type: "text",
    prompt: "What are dreams?",
    content: "Dreams are stories your brain tells you when you're sleeping. It uses your memories and makes them into adventures. Sometimes they're silly and don't make sense and that's okay!",
    source: "ai",
    context: "Generated by Claude",
    funFact: "AI models don't dream... or do they?"
  },
  {
    id: 17,
    type: "text",
    prompt: "Why do we have to sleep?",
    content: "Because your body is like a phone and you gotta charge it. If you don't sleep you get grumpy and your brain stops working good. Also monsters can only get you if you're not in bed so.",
    source: "child",
    context: "By Noah, age 7",
    funFact: "Noah's monster theory has flawless kid logic"
  },
  {
    id: 18,
    type: "text",
    prompt: "Why do we have to sleep?",
    content: "Sleep is when your body fixes itself and grows bigger. Your brain also practices things you learned that day. Without sleep, you'd be super tired and forgetful like a sleepy bear!",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "The 'sleepy bear' simile gave this one away in testing"
  },
  {
    id: 19,
    type: "text",
    prompt: "Where do babies come from?",
    content: "From mommy's tummy! She eats a special seed and it grows into a baby like a plant. Then when it's big enough the doctor takes it out. I think.",
    source: "child",
    context: "By Isabella, age 6",
    funFact: "Isabella's parents were relieved this was her understanding"
  },
  {
    id: 20,
    type: "text",
    prompt: "Where do babies come from?",
    content: "Babies grow inside their mommy's tummy in a special place called a womb. It takes about 9 months for them to get big enough to come out. They start super tiny!",
    source: "ai",
    context: "Generated by Claude (very carefully)",
    funFact: "AI was instructed to keep this G-rated"
  },
  {
    id: 21,
    type: "text",
    prompt: "What is a rainbow?",
    content: "It's when the sun and rain get married in the sky and make a colorful bridge. Leprechauns hide gold at the end but no one can find it because rainbows are tricky.",
    source: "child",
    context: "By Ethan, age 5",
    funFact: "Ethan spent an entire afternoon trying to reach a rainbow's end"
  },
  {
    id: 22,
    type: "text",
    prompt: "Why do dogs bark?",
    content: "Because they can't talk like us! Barking is dog language. One bark means 'hi' and lots of barks means 'THERE'S A SQUIRREL!!!!!' or maybe 'give me food please.'",
    source: "child",
    context: "By Lily, age 6",
    funFact: "Lily has catalogued 17 different bark meanings"
  },
  {
    id: 23,
    type: "text",
    prompt: "Why do dogs bark?",
    content: "Dogs bark to talk since they can't use words. They bark when they're happy, scared, excited, or want attention. Every bark means something different if you listen carefully!",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "This response was flagged as 'too educational'"
  },
  {
    id: 24,
    type: "text",
    prompt: "What is thunder?",
    content: "It's clouds bumping into each other and going OW really loud. Or sometimes angels are bowling. My grandpa said it's God moving furniture but I think he was joking.",
    source: "child",
    context: "By Mason, age 5",
    funFact: "Mason covers his ears during 'angel bowling tournaments'"
  },
  {
    id: 25,
    type: "text",
    prompt: "What is thunder?",
    content: "Thunder is the sound that lightning makes! When lightning zaps through the sky, it's so hot it makes the air explode with a big BOOM sound that we call thunder.",
    source: "ai",
    context: "Generated by Claude",
    funFact: "The 'BOOM' sound effect was added for authenticity"
  },
  // DRAWING CONTENT
  {
    id: 26,
    type: "drawing",
    prompt: "Draw a cat",
    content: "cat-child",
    source: "child",
    context: "By Zoe, age 5",
    funFact: "Zoe insists cats have exactly 3 whiskers on each side"
  },
  {
    id: 27,
    type: "drawing",
    prompt: "Draw a cat",
    content: "cat-ai",
    source: "ai",
    context: "Generated by DALL-E (children's style prompt)",
    funFact: "AI was asked to draw 'like a kindergartener'"
  },
  {
    id: 28,
    type: "drawing",
    prompt: "Draw a house",
    content: "house-child",
    source: "child",
    context: "By Benjamin, age 6",
    funFact: "Benjamin's house has 47 windows because he likes windows"
  },
  {
    id: 29,
    type: "drawing",
    prompt: "Draw a house",
    content: "house-ai",
    source: "ai",
    context: "Generated by Midjourney (child art style)",
    funFact: "The AI couldn't resist making the smoke too perfect"
  },
  {
    id: 30,
    type: "drawing",
    prompt: "Draw a family",
    content: "family-child",
    source: "child",
    context: "By Ava, age 4",
    funFact: "Ava drew herself bigger than her parents because she's 'the boss'"
  },
  {
    id: 31,
    type: "drawing",
    prompt: "Draw the sun",
    content: "sun-child",
    source: "child",
    context: "By Jack, age 5",
    funFact: "Jack adds sunglasses to his suns because 'the sun is cool'"
  },
  {
    id: 32,
    type: "drawing",
    prompt: "Draw a flower",
    content: "flower-ai",
    source: "ai",
    context: "Generated by DALL-E (preschool style)",
    funFact: "AI perfectly centered the flower - dead giveaway"
  },
  {
    id: 33,
    type: "drawing",
    prompt: "Draw a dog",
    content: "dog-child",
    source: "child",
    context: "By Charlotte, age 6",
    funFact: "Charlotte's dog has 5 legs because 'he's a fast runner'"
  },
  {
    id: 34,
    type: "drawing",
    prompt: "Draw a rainbow",
    content: "rainbow-child",
    source: "child",
    context: "By William, age 5",
    funFact: "William added purple twice because it's his favorite"
  },
  {
    id: 35,
    type: "drawing",
    prompt: "Draw a tree",
    content: "tree-ai",
    source: "ai",
    context: "Generated by Stable Diffusion (kid drawing style)",
    funFact: "The symmetry gave it away in 80% of tests"
  },
  {
    id: 36,
    type: "text",
    prompt: "Why is water wet?",
    content: "Because that's its job! Water's job is to be wet and make other stuff wet too. If water wasn't wet it would just be air probably.",
    source: "child",
    context: "By Harper, age 6",
    funFact: "Harper's logic is philosophically hard to argue with"
  },
  {
    id: 37,
    type: "text",
    prompt: "What makes you happy?",
    content: "Puppies and ice cream and when daddy makes funny faces and finding a really good stick and bubbles and when its my birthday and macaroni and cheese especially the orange kind.",
    source: "child",
    context: "By James, age 5",
    funFact: "James's 'really good stick' collection has 23 sticks"
  },
  {
    id: 38,
    type: "text",
    prompt: "What makes you happy?",
    content: "Playing with friends makes me super happy! Also eating yummy food, getting hugs, playing with toys, and when someone tells me I did a good job. Sunny days are nice too!",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "The organized list structure hints at AI origins"
  },
  {
    id: 39,
    type: "drawing",
    prompt: "Draw a person",
    content: "person-child",
    source: "child",
    context: "By Evelyn, age 4",
    funFact: "Evelyn draws everyone with circle bodies and stick arms"
  },
  {
    id: 40,
    type: "drawing",
    prompt: "Draw a car",
    content: "car-ai",
    source: "ai",
    context: "Generated by DALL-E (child's drawing style)",
    funFact: "The wheels are too perfectly round - real kids draw ovals"
  },
  {
    id: 41,
    type: "text",
    prompt: "What do you want to be when you grow up?",
    content: "A dinosaur doctor who also does magic and has a pet dragon and works at an ice cream store on weekends. And maybe a firefighter truck (not firefighter, the actual truck).",
    source: "child",
    context: "By Henry, age 5",
    funFact: "Henry has been consistent about the firefighter truck thing for 2 years"
  },
  {
    id: 42,
    type: "text",
    prompt: "What do you want to be when you grow up?",
    content: "I want to be a teacher so I can help kids learn cool stuff! Or maybe a scientist who discovers new animals. Being an astronaut would be really cool too because space is amazing!",
    source: "ai",
    context: "Generated by Claude",
    funFact: "The exclamation points and enthusiasm feel authentic but the choices are too sensible"
  },
  {
    id: 43,
    type: "text",
    prompt: "Why is grass green?",
    content: "Because it eats the green stuff from the sun. The sun gives it green vitamins I think. And if you eat grass you'll turn green too but don't do it cause it tastes bad I tried.",
    source: "child",
    context: "By Amelia, age 6",
    funFact: "Amelia was disappointed when eating grass didn't work"
  },
  {
    id: 44,
    type: "text",
    prompt: "Why is grass green?",
    content: "Grass has special stuff called chlorophyll that's green. It uses this to eat sunlight and make food for itself. It's like the grass's own kitchen that happens to be green colored!",
    source: "ai",
    context: "Generated by GPT-4",
    funFact: "Using 'chlorophyll' even with a child explanation gave this away"
  },
  {
    id: 45,
    type: "drawing",
    prompt: "Draw a butterfly",
    content: "butterfly-child",
    source: "child",
    context: "By Sophia, age 5",
    funFact: "Sophia's butterflies always have exactly 6 colors"
  }
];

// Function to get random items for a game
export function getRandomGameItems(count: number = 10): GameContent[] {
  const shuffled = [...gameContent].sort(() => Math.random() - 0.5);
  return shuffled.slice(0, count);
}
